In [1]:
import numpy as np
import matplotlib
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import datasets, linear_model, preprocessing
from sklearn.preprocessing import PolynomialFeatures, OrdinalEncoder
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
%matplotlib inline

# Load the standard packages for working with data

In [2]:
from pandas.core.indexing import length_of_indexer
df = pd.read_csv("Breast_Cancer.csv")

data = np.array(df)
X = data[:,0:data.shape[1]-1]
y = data[:, -1]
print(X.shape)
print(y.shape)

df.head()

(4024, 13)
(4024,)


Age T Stage  N Stage 6th Stage              differentiate Grade   A Stage  \
0   68       T1      N1       IIA      Poorly differentiated     3  Regional   
1   50       T2      N2      IIIA  Moderately differentiated     2  Regional   
2   58       T3      N3      IIIC  Moderately differentiated     2  Regional   
3   58       T1      N1       IIA      Poorly differentiated     3  Regional   
4   47       T2      N1       IIB      Poorly differentiated     3  Regional   

   Tumor Size Estrogen Status Progesterone Status  Regional Node Examined  \
0           4        Positive            Positive                      24   
1          35        Positive            Positive                      14   
2          63        Positive            Positive                      14   
3          18        Positive            Positive                       2   
4          41        Positive            Positive                       3   

   Reginol Node Positive  Survival Months Status  
0                      1               60  Alive  
1                      5               62  Alive  
2                      7               75  Alive  
3                      1               84  Alive  
4                      1               50  Alive

# Encoding Labels And Target 

In [19]:
# T-Stage: The T refers to the size and extent of the main tumor
# N-Stage:  lymph nodes before they reach other parts of the body. 
# The N category can be assigned a letter or a number: 
# NX means there's no information about the nearby lymph nodes
#6th stage: IIA, IIB, IIIA, IIIB, IIIC
#Differentiate: Poorly differentiated, Moderately differentiated, Well differentiated
#Regional or Distant

In [49]:

from sklearn.preprocessing import LabelEncoder


#enc = OrdinalEncoder().fit(X[:,1].reshape(-1,1))


#enc.categories_=[["T1","T2","T3"],[1, 2,3]]

#X[:,1]= enc.transform(X[:,1].reshape(-1,1)).reshape(1,-1)


# X = np.where(X =="T1",1,X)
# X = np.where(X =="T2",2,X)
# X = np.where(X =="T3",3,X)
# X = np.where(X =="T4",4,X)

# X = np.where(X =="N1",1,X)
# X = np.where(X =="N2",2,X)
# X = np.where(X =="N3",3,X)

# X = np.where(X =="IIIC",5,X)
# X = np.where(X =="IIIB",4,X)
# X = np.where(X =="IIIA",3,X)

# X = np.where(X =="IIB",2,X)
# X = np.where(X =="IIA",1,X)

# X = np.where(X=="Undifferentiated",1,X)
# X = np.where(X =="Poorly differentiated",2,X)
# X = np.where(X =="Moderately differentiated",3,X)
# X = np.where(X =="Well differentiated",4,X)
# X = np.where(X==" anaplastic; Grade IV",4,X)
# lb = preprocessing.LabelBinarizer(neg_label=-1, pos_label=0)  # Binary encoding
# X[:,6] = np.abs(lb.fit_transform(X[:,6])).reshape(4024,)
# lb = preprocessing.LabelBinarizer(neg_label=-1, pos_label=0)  # Binary encoding
# X[:,8] = np.abs(lb.fit_transform(X[:,8])).reshape(4024,)
# lb = preprocessing.LabelBinarizer(neg_label=-1, pos_label=0)  # Binary encoding
# X[:,9] = np.abs(lb.fit_transform(X[:,9])).reshape(4024,)
# lb = preprocessing.LabelBinarizer(neg_label=-1, pos_label=0)  # Binary encoding
# y = np.abs(lb.fit_transform(y)).reshape(4024,)

label_encoder_race = LabelEncoder()
label_encoder_marital_status = LabelEncoder()
label_encoder_t_stage = LabelEncoder()
label_encoder_n_stage = LabelEncoder()
label_encoder_6th_stage = LabelEncoder()
label_encoder_differentiate = LabelEncoder()
label_encoder_grade = LabelEncoder()
label_encoder_a_stage = LabelEncoder()
label_encoder_estrogene = LabelEncoder()
label_encoder_progesterone = LabelEncoder()
label_encoder_status = LabelEncoder()

X[:,1] = label_encoder_race.fit_transform(X[:,1])
X[:,2] = label_encoder_marital_status.fit_transform(X[:,2])
X[:,3] = label_encoder_t_stage.fit_transform(X[:,3])
X[:,4] = label_encoder_n_stage.fit_transform(X[:,4])
#X[:,5] = label_encoder_6th_stage.fit_transform(X[:,5])
X[:,6] = label_encoder_differentiate.fit_transform(X[:,6])
X[:,7] = label_encoder_grade.fit_transform(X[:,7])
X[:,8] = label_encoder_a_stage.fit_transform(X[:,8])
X[:,10] = label_encoder_estrogene.fit_transform(X[:,10])
X[:,11] = label_encoder_progesterone.fit_transform(X[:,11])

y = label_encoder_status.fit_transform(y)

print(X)


[[68 0 0 ... 23 0 60]
 [50 1 1 ... 13 4 62]
 [58 2 2 ... 13 6 75]
 ...
 [68 1 0 ... 10 2 69]
 [58 1 0 ... 10 0 72]
 [46 1 0 ... 6 1 100]]


In [32]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_standard = scaler.fit_transform(X)

In [33]:
X_train_val, X_test, y_train_val, y_test = train_test_split(
    X, y,test_size = 0.07, random_state=10, shuffle=True)

X_train, X_val, y_train, y_val = train_test_split(
    X_train_val, y_train_val, test_size = 0.07, random_state=10, shuffle=True)

# PCA

In [6]:
from sklearn.decomposition import PCA

In [9]:
SEED = 23
pca = PCA(random_state=SEED)

pca.fit(X_train)

X_train_red = pca.transform(X_train)
X_val_red = pca.transform(X_val)

In [10]:
fit_pred_evaluate(model, X_train_red, y_train, X_val_red, y_val, train_label="Training Data - PCA", test_label="Validation Data - PCA", graph_valutation_test=True)

NameError: name 'fit_pred_evaluate' is not defined

# Logistic Regression

In [6]:
logreg = LogisticRegression(C=100000000,max_iter=1000)
logreg.fit(X_train, y_train)
y_hat_logreg = logreg.predict(X_train)
acc_logreg = logreg.score(X_train, y_train)
print("Q18 - Accuracy on training data = %f" % acc_logreg)

Q18 - Accuracy on training data = 0.896264


In [7]:
w_logreg = logreg.coef_ 
intercept_logreg = logreg.intercept_ 
print('Q19 - w_logreg: ', w_logreg) 
print('Q19 - intercept_logreg: ', intercept_logreg) 
print(y_hat_logreg)

Q19 - w_logreg:  [[-0.02510384 -0.58014447 -0.51836302  0.20041227  0.35043914 -0.16892517
   0.32470169  0.00719249 -0.39304342 -0.55056814  0.02799005 -0.08514777
   0.06115714]]
Q19 - intercept_logreg:  [0.03630279]
[1 1 1 ... 1 1 1]


# SVM


In [34]:
from sklearn.svm import SVC # "Support vector classifier"

# Create a classifier: a support vector classifier
svc = SVC(probability=False, C=1000, kernel="rbf",verbose=20)

In [35]:
svc.fit(X_train,y_train)

[LibSVM]...............................................................................................................................................................................*................................................................................................................................................................................................................................................*
optimization finished, #iter = 415252
obj = -728950.748982, rho = -3.615068
nSV = 820, nBSV = 681
Total nSV = 820


SVC(C=1000, verbose=20)

In [36]:
yhat_val = svc.predict(X_val)
yhat_test= svc.predict(X_test)


In [37]:
acc_val = np.mean(yhat_val  == y_val)
acc_test= np.mean(yhat_test  == y_test)

print('Accuaracy on the valdtion Data= {0:f}'.format(acc_val))
print('Accuaracy on the test Data= {0:f}'.format(acc_test))

Accuaracy on the valdtion Data= 0.893130
Accuaracy on the test Data= 0.893617


# Nerual Networks

In [38]:
from sklearn.metrics import accuracy_score
import numpy.random as r


# One-vs-all encoding

### One-vs-all encoding
Our target is an integer in the range [0,..,9], so we will have 10 output neuron's in our network.  

-  If  $y=0$, we want the output neurons to have the values $(1,0,0,0,0,0,0,0,0,0)$

-  If  $y=1$ we want the output neurons to have the values $(0,1,0,0,0,0,0,0,0,0)$
-  etc

Thus we need to change our target so it is the same as our hoped for output of the neural network.  
-  If $y=0$ we change it into the vector $(1,0,0,0,0,0,0,0,0,0)$. 
-  If $y=1$ we change it into the vector $(0,1,0,0,0,0,0,0,0,0)$
-  etc

See page 29 from the website listed above

The code to covert the target vector

In [39]:
def convert_y_to_vect(y):
    y_vect = np.zeros((len(y), 10))
    for i in range(len(y)):
        y_vect[i, y[i]] = 1
    return y_vect

In [40]:
y_v_train = convert_y_to_vect(y_train)
y_v_test = convert_y_to_vect(y_test)
print(y_train[0:4])
print(y_v_train[0:4])

[1 1 1 1]
[[0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]]


# Creating the neural network

### The activation function and its derivative

We will use the sigmoid activation function:  $f(z)=\frac{1}{1+e^{-z}}$

The deriviative of the sigmoid function is: $f'(z) = f(z)(1-f(z))$ 

In [41]:
def f(z):
    return 1 / (1 + np.exp(-z))


def f_deriv(z):
    return f(z) * (1 - f(z))

### Creating and initialing W and b
We want the weights in W to be different so that during back propagation the nodes on a level will have different gradients and thus have different update values.

We want the  weights to be small values, since the sigmoid is almost "flat" for large inputs.

Next is the code that assigns each weight a number uniformly drawn from $[0.0, 1.0)$.  The code assumes that the number of neurons in each level is in the python list *nn_structure*.

In the code, the weights, $W^{(\ell)}$ and $b^{(\ell)}$ are held in a python dictionary

In [42]:
def setup_and_init_weights(nn_structure):
    W = {} #creating a dictionary i.e. a set of key: value pairs
    b = {}
    for l in range(1, len(nn_structure)):
        W[l] = r.random_sample((nn_structure[l], nn_structure[l-1])) #Return “continuous uniform” random floats in the half-open interval [0.0, 1.0). 
        b[l] = r.random_sample((nn_structure[l],))
    return W, b

### Initializing $\triangledown W$ and $\triangledown b$
Creating $\triangledown W^{(\ell)}$ and $\triangledown b^{(\ell)}$ to have the same size as $W^{(\ell)}$ and $b^{(\ell)}$, and setting $\triangledown W^{(\ell)}$, and  $\triangledown b^{(\ell)}$ to zero

In [43]:
def init_tri_values(nn_structure):
    tri_W = {}
    tri_b = {}
    for l in range(1, len(nn_structure)):
        tri_W[l] = np.zeros((nn_structure[l], nn_structure[l-1]))
        tri_b[l] = np.zeros((nn_structure[l],))
    return tri_W, tri_b

## Feed forward
Perform a forward pass throught the network.  The function returns the values of $a$ and $z$

In [44]:
def feed_forward(x, W, b):
    a = {1: x} # create a dictionary for holding the a values for all levels
    z = { } # create a dictionary for holding the z values for all the layers
    for l in range(1, len(W) + 1): # for each layer
        node_in = a[l]
        z[l+1] = W[l].dot(node_in) + b[l]  # z^(l+1) = W^(l)*a^(l) + b^(l)
        a[l+1] = f(z[l+1]) # a^(l+1) = f(z^(l+1))
    return a, z

## Compute $\delta$
The code below compute $\delta^{(s_l)}$ in a function called "calculate_out_layer_delta",  and  computes $\delta^{(\ell)}$ for the hidden layers in the function called "calculate_hidden_delta".  

If we wanted to have a different cost function, we would change the "calculate_out_layer_delta" function.

In [45]:
def calculate_out_layer_delta(y, a_out, z_out):
    # delta^(nl) = -(y_i - a_i^(nl)) * f'(z_i^(nl))
    return -(y-a_out) * f_deriv(z_out) 


def calculate_hidden_delta(delta_plus_1, w_l, z_l):
    # delta^(l) = (transpose(W^(l)) * delta^(l+1)) * f'(z^(l))
    return np.dot(np.transpose(w_l), delta_plus_1) * f_deriv(z_l)

## The Back Propagation Algorithm

In [46]:
def train_nn(nn_structure, X, y, iter_num=3000, alpha=0.25):
    W, b = setup_and_init_weights(nn_structure)
    cnt = 0
    N = len(y)
    avg_cost_func = []
    print('Starting gradient descent for {} iterations'.format(iter_num))
    while cnt < iter_num:
        if cnt%1000 == 0:
            print('Iteration {} of {}'.format(cnt, iter_num))
        tri_W, tri_b = init_tri_values(nn_structure)
        avg_cost = 0
        for i in range(N):
            delta = {}
            # perform the feed forward pass and return the stored a and z values, to be used in the
            # gradient descent step
            a, z = feed_forward(X[i, :], W, b)
            # loop from nl-1 to 1 backpropagating the errors
            for l in range(len(nn_structure), 0, -1):
                if l == len(nn_structure):
                    delta[l] = calculate_out_layer_delta(y[i,:], a[l], z[l])
                    avg_cost += np.linalg.norm((y[i,:]-a[l]))
                else:
                    if l > 1:
                        delta[l] = calculate_hidden_delta(delta[l+1], W[l], z[l])
                    # triW^(l) = triW^(l) + delta^(l+1) * transpose(a^(l))
                    tri_W[l] += np.dot(delta[l+1][:,np.newaxis], np.transpose(a[l][:,np.newaxis]))# np.newaxis increase the number of dimensions
                    # trib^(l) = trib^(l) + delta^(l+1)
                    tri_b[l] += delta[l+1]
        # perform the gradient descent step for the weights in each layer
        for l in range(len(nn_structure) - 1, 0, -1):
            W[l] += -alpha * (1.0/N * tri_W[l])
            b[l] += -alpha * (1.0/N * tri_b[l])
        # complete the average cost calculation
        avg_cost = 1.0/N * avg_cost
        avg_cost_func.append(avg_cost)
        cnt += 1
    return W, b, avg_cost_func

In [47]:
def predict_y(W, b, X, n_layers):
    N = X.shape[0]
    y = np.zeros((N,))
    for i in range(N):
        a, z = feed_forward(X[i, :], W, b)
        y[i] = np.argmax(a[n_layers])
    return y

## Running the neural network

Our code assumes the size of each layer in our network is held in a list.  The input layer will have 64 neurons (one for each pixel in our 8 by 8 pixelated digit).  Our hidden layer has 30 neurons (you can change this value).  The output layer has 10 neurons.

Next we create the python list to hold the number of neurons for each level and then run the neural network code with our training data.

This code will take some time...

In [48]:
nn_structure = [13,5,1]
    
# train the NN
W, b, avg_cost_func = train_nn(nn_structure, X_train, y_v_train, 3000)

Starting gradient descent for 3000 iterations
Iteration 0 of 3000


TypeError: can't multiply sequence by non-int of type 'float'

### Plotting the learning curve

In [ ]:
# plot the avg_cost_func
plt.plot(avg_cost_func)
plt.ylabel('Average J')
plt.xlabel('Iteration number')
plt.show()

## Assessing accuracy
Next we determine what percentage the neural network correctly predicted the handwritten digit correctly on the test set

In [ ]:
# get the prediction accuracy and print
y_pred = predict_y(W, b, X_test, 3)
print('Prediction accuracy is {}%'.format(accuracy_score(y_test, y_pred) * 100))

In [ ]:

# first neural network with keras tutorial
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [56]:
! python3 -m pip install tensorflow

     |████████████████████████████████| 244.3 MB 33.5 MB/s eta 0:00:01   |███▎                            | 25.2 MB 1.4 MB/s eta 0:02:39     |█████▎                          | 40.5 MB 248 kB/s eta 0:13:42     |██████▎                         | 47.6 MB 1.5 MB/s eta 0:02:15  | 58.7 MB 133 kB/s eta 0:23:06     |████████████▉                   | 98.1 MB 55.2 MB/s eta 0:00:03     |█████████████████▌              | 133.2 MB 42.2 MB/s eta 0:00:03| 207.5 MB 30.1 MB/s eta 0:00:02
     |████████████████████████████████| 1.6 MB 25.8 MB/s eta 0:00:01
     |████████████████████████████████| 6.0 MB 16.4 MB/s eta 0:00:01
     |████████████████████████████████| 57 kB 18.9 MB/s eta 0:00:01
     |████████████████████████████████| 1.7 MB 26.2 MB/s eta 0:00:01
     |████████████████████████████████| 13.2 MB 5.8 MB/s eta 0:00:01
     |████████████████████████████████| 439 kB 25.4 MB/s eta 0:00:01
     |████████████████████████████████| 124 kB 24.7 MB/s eta 0:00:01
     |████████████████████████████████| 65